### ISSUE TITLE
ARM architecture

### ISSUE THREAD

**Issue by SaturnusDJ** [Thom-x/docker-fr24feed-piaware-dump1090-mutability#2]
Any plans for ARM architecture?

**Comment by Thom-x** [comment]
No, not for now (I don't have any Rpi), but you can look at forks, some of
them are compatible with it.

**Comment by SaturnusDJ** [comment]
Ah, https://github.com/dmorehouse/docker-raspberrypi-fr24feed-piaware-dump1090-mutability --> https://hub.docker.com/r/dmorehouse/raspberrypi-flightradar-flightaware-feed

Will test.
