### ISSUE TITLE
http://www.heywhatsthat.com / Terrain-limit rings

### ISSUE THREAD

**Issue by SaturnusDJ** [Thom-x/docker-fr24feed-piaware-dump1090-mutability#3]
Can you please explain how http://www.heywhatsthat.com / Terrain-limit rings is used? What are the implications?

**Comment by Thom-x** [comment]
It allow you to see the theorical range where can see planes.
You can see an example on https://github.com/Thom-x/docker-fr24feed-piaware-dump1090-mutability/blob/master/screenshot.png.

The website is not available, but it create a json representing this range according to your antenna position.

**Comment by SaturnusDJ** [comment]
Ah ok. Is hardware like antenna also taken in consideration when using the data?

**Comment by Thom-x** [comment]
No, it's only the filed of view, the new url is now https://www.heywhatsthat.com/
